package no.nav.bidrag.domene.enums.behandling

import io.swagger.v3.oas.annotations.media.Schema

// Enum verdier av tabellen T_KODE_BESL_AARSAK i bisys
@Schema(enumAsRef = true)
enum class Beslutningsårsak(
    val bisysKode: String,
    val beskrivelse: String,
) {
    ANNET_AVSLAG("A", "Annet avslag"),
    ANNET_AVSLAG_ALT("AA", "Annet avslag"),
    AVSLAG_MANGLENDE_BIDRAGSPLIKTIGER("AB", "Avsl mang.bidrevne"),
    AVSLAG_BARNEPENSJON("ABA", "Avslag, på grunn av barnepensjon"),
    MANGLER_BIDRAGSEVNE("ABB", "Mangler bidragsevne"),
    AVSLAG_BARNETS_EKTESKAP("ABE", "Avslag, barnets ekteskap"),
    AVSLAG_BARNETS_INNTEKT("ABI", "Avslag, barnets inntekt"),
    IKKE_FULL_BIDRAGSEVNE("ABS", "Ikke full bidragsevne"),
    BARNET_HAR_INNTEKT("ABX", "Barnet har inntekt"),
    UTGIFTER_DEKKES_AV_BARNEBIDRAGET("ADB", "Utgifter dekkes av barnebidraget"),
    AVSLAG_YTELSE_FRA_FOLKETRYGDEN("AFT", "Avslag, på grunn av ytelse fra folketrygden"),
    AVSLAG_FULLT_UNDERHOLDT_AV_OFFENTLIG("AFU", "Avslag, fullt underholdt av offentlig"),
    AVSLAG("AG", "Avslag"),
    AVSLAG_HØY_INNTEKT("AHI", "Avslag, høy inntekt"),
    IKKE_DOKUMENTERT("AID", "Ikke dokumentert"),
    IKKE_NØDVENDIGE_UTGIFTER("AIN", "Ikke nødvendige utgifter"),
    AVSLAG_IKKE_OMSORG("AIO", "Avslag, ikke omsorg"),
    AVSLAG_IKKE_OPPHOLD_I_RIKET("AIR", "Avslag, ikke opphold i riket"),
    IKKE_UNDERHOLDSPLIKT("AIU", "Ikke underholdsplikt"),
    AVKLART("AK", "Avklart"),
    AVSLAG_MANGLENDE_DOKUMENTASJON("AMD", "Avslag, manglende dokumentasjon"),
    GODKJENT_BELØP_LAVERE_ENN_FORSKUDDSSATS("AMF", "Godkjent beløp er lavere enn forskuddssats"),
    ANERKJENT("AN", "Anerkjent"),
    AVSLAG_SØKNAD_OPPHØR("AO", "Avsl søkn.opphør"),
    AVSLAG_BARNET_BOR_SAMMEN_MED_BEGGE_FORELDRENE("ASA", "Avs, barnet anses å bo sammen med begge foreldrene"),
    AUTOMATISK_AVSLAG("AUA", "Automatisk avslag"),
    ALLE_UTGIFTER_FORELDET("AUF", "Alle utgifter er foreldet"),
    AVSLAG_OPPHOLD_I_UTLANDET("AUT", "Avslag, opphold i utlandet"),
    AVSLAG_UTENLANDSK_YTELSE("AUY", "Avslag, utenlandsk ytelse"),
    AVVIST("AV", "Avvist"),
    AVSLUTTET("AVS", "Avsluttet"),
    AVSLAG_FREMTIDIG_BIDRAGSEVNE("A1", "Avsl fremt.bidr.evne"),
    AVSLAG_OVER_18_ÅR("A18", "Avslag, over 18 år"),
    AVSLAG_HAR_BIDRAGSEVNE("A2", "Avsl har bidr.evne"),
    BETINGELSE_ANNULLERT_BP_I_UTLAND("BA", "Bet.anm. BP i utl"),
    DELVIS_ETTERGIVELSE("DE", "Delvis ettergivelse"),
    ENDRET("EE", "Endret"),
    FB_KONVENSJON("FBK", "FB konv."),
    ENDRET_FARSKAP("FE", "Endret farskap"),
    HENLAGT_FARSKAP("FH", "Henlagt farskap"),
    FEILREGISTRERT("FR", "Feilregistrert"),
    FRITATT_IKKE_SØKT("GIFR", "Fritatt, ikke søkt"),
    ILAGT_IKKE_SØKT("GIGI", "Ilagt, ikke søkt"),
    FRITATT_ETTER_KLAGE("GKFI", "Fritatt etter klage"),
    IKKE_FRITATT_ETTER_KLAGE("GKIF", "Ikke fritatt e klage"),
    FRITATT_SØKT("GSFR", "Fritatt, søkt"),
    ILAGT_DOKUMENTASJON_MANGLER("GSGD", "Ilagt, dok. mangler"),
    ILAGT_HØY_INNTEKT("GSHI", "Ilagt, høy inntekt"),
    FULL_ETTERGIVELSE("HE", "Full ettergivelse"),
    INNVILGET("I", "Innvilget"),
    IKKE_AVKLART("IAK", "Ikke avklart"),
    IKKE_ANERKJENT("IAN", "Ikke anerkjent"),
    INNKREVING_SENDT_UTLANDET("IB", "Innkr sendt utl."),
    INGEN_ENDRING("IE", "Ingen endring"),
    INNKREVING_GJELD("IG", "Innkreving gjeld"),
    INDEKSREGULERING("IREG", "Indeksregulering"),
    INDEKSREGULERING_KONVENSJON("IRK", "Ind.reg. konv"),
    IKKE_TILBAKEKREVING("IT", "Ikke tilbakekreving"),
    INNVILGET_VEDTAK("IV", "Innvilget vedtak"),
    KOSTNADSBEREGNING_BIDRAG("KBB", "Kostn.beregn.bidrag"),
    HENLAGT_MORSKAP("MH", "Henlagt morskap"),
    OPPHØR_AVTALE_DIREKTE_BETALING("OA", "Opph avt direkte bet"),
    OPPHØR_DIREKTE_BETALING("OB", "Opph direkte bet"),
    OPPHØR_BARNEPENSJON("OBA", "Opphør, på grunn av barnepensjon"),
    OPPHØR_BARNETS_EKTESKAP("OBE", "Opphør, barnets ekteskap"),
    OPPHØR_BARNETS_INNTEKT("OBI", "Opphør, barnets inntekt"),
    OPPHØR_BP_DØD("OD", "Opph BP død"),
    OPPHØR_BARN_FLYTTER("OF", "Opph barn flytter"),
    OPPHØR_YTELSE_FRA_FOLKETRYGDEN("OFT", "Opphør, på grunn av ytelse fra folketrygden"),
    OPPHØR_FULLT_UNDERHOLDT_AV_OFFENTLIG("OFU", "Opphør, fullt underholdt av offentlig"),
    OPPHØR_ANNET("OH", "Opphør annet"),
    OPPHØR("OHE", "Opphør"),
    OPPHØR_HØY_INNTEKT("OHI", "Opphør, høy inntekt"),
    OPPHØR_SKOLE_18_ÅR("OHS", "Opph skole 18 år"),
    OPPHØR_OVER_18_ÅR("OH2", "Opphør, over 18 år"),
    OPPHØR_ANNEN_ÅRSAK("OH3", "Opph annen årsak"),
    OPPHØR_IKKE_OMSORG("OIO", "Opphør, ikke omsorg"),
    OPPHØR_IKKE_OPPHOLD_I_RIKET("OIR", "Opphør, ikke opphold i riket"),
    FORDELING_VEDTATT("FV", "Fordeling vedtatt"),
    MEDHOLD("MED", "Medhold"),
    OPPHØR_MANGLENDE_DOKUMENTASJON("OMD", "Opphør, manglende dokumentasjon"),
    OPPHØR_FLYTTER_SAMMEN("OS", "Opph flytter sammen"),
    OPPHØR_BOR_SAMMEN_MED_BEGGE_FORELDRENE("OSA", "Opp, barnet anses å bo sammen med begge foreldrene"),
    OPPHØR_BM_ØNSKER_DET("OU", "Opph BM's ønske"),
    OPPHØR_OPPHOLD_I_UTLANDET("OUT", "Opphør, opphold i utlandet"),
    OPPHØR_UTENLANDSK_YTELSE("OUY", "Opphør, utenlandsk ytelse"),
    OVERGANGSREGEL("OVR", "Overgangsregel"),
    BIDRAG_VURDERT_OPP_FORSKNING("RFO", "Bidr vurd opp forsk"),
    STADFESTELSE("SF", "Stadfestelse"),
    KLAGE_AVVIST("TA", "Klagen avvist"),
    TILBAKEKREVING("TB", "Tilbakekreving"),
    TILBAKEKREVING_BIDRAG("TC", "Tilbakekreving bidrag"),
    SAKEN_TRUKKET("TR", "Saken trukket"),
    UTENLANDSK_AVGJØRELSE("UA", "Utenlandsk avgjørelse"),
    VEDTAK_VANLIG_INNKREVING("V", "Vedtak vanlig innkr."),
    VEDTAK_MIDLERTIDIG("VM", "Vedtak midlertidig"),
    INGEN_ENDRING_UNDER_GRENSE("VO", "Ingen endring under grense"),
    SÆRTILSKUDD_INNVILGET("VS", "Særtilskudd innvilget"),
    VEDTAK_INNKREVING_SÆRTILSKUDD("VS1", "Vedt innkr.særtils"),
    INNTIL_1_ÅR_TILBAKE("VT", "Inntil 1 år tilbake"),
    PRIVAT_AVTALE("VX", "Privat avtale"),
    VEDTAK_INNKREVING_AVTALE_DOM("VX1", "Vedt innkr.avt/dom"),
    VEDTAK_INNKREVING_BOR_I_SAM("V1", "Vedt innkr.bor i sam"),
    VEDTAK_INNKREVING_BM_FORSKNING("V2", "Vedt innkr.BM forsk"),
    AVSLAG_18_ÅR("X18", "Avslag, 18 år"),
    FORHØYET_FORSKUDD("100", "Forhøyet forskudd"),
    BP_BARNETILLEGG("101", "BP barnetillegg"),
    BM_BARNETILLEGG("102", "BM barnetillegg"),
    SKJØNN_UTLANDET("11B", "Skjønn,Utlandet"),
    SKJØNN_BARN_FORSØRGER("11C", "Skjønn,barn fors."),
    AVSLAG_TILLEGGSBIDRAG("12A", "Avslag tilleggsbid"),
    INNVILGET_TILLEGGSBIDRAG("12I", "Innvilg.tilleggsbid"),
    MAKSIMALT_BIDRAG_PR_BARN("12M", "Maks.bidrag pr.ba"),
    FORHØYET_FORSKUDD_VED_11_ÅR("125", "Forhøyet forskudd ved 11 år"),
    VEDTAK_INNKREVING_18_ÅR("18", "Vedtak innkr.18år"),
    PROCENT_200("200", "200 %"),
    PROCENT_250_VED_11_ÅR("250", "250% ved 11 år"),
    INNTEKT_MANGLER_BEGGE("4D", "Innt.mangl.begge"),
    MANGLENDE_INNTEKT_EVNE("4DE", "Mangl.innt.evne"),
    INNTEKT_BP_MANGLENDE_DOKUMENTASJON("4D1", "Innt.BP mang.dok"),
    INNTEKT_BM_MANGLENDE_DOKUMENTASJON("4D2", "Innt.BM mang.dok"),
    LAV_INNTEKTEVNE_BEGGE("4E", "Lav inntevne begge"),
    LAV_INNTEKTEVNE_BP("4E1", "Lav inntevne BP"),
    LAV_INNTEKTEVNE_BM("4E2", "Lav inntevne BM"),
    BARNET_ER_SELVFORSØRGET("5SF", "Barnet er selvforsørget"),
    REDUSERT_FORSKUDD("50", "Redusert forskudd"),
    MANGLENDE_BIDRAGSEVNE_ALT("6MB", "Mangl bidragsevne"),
    MAKSIMALT_25_PROSENT_AV_INNTEKT("7M", "Maks25% av innt"),
    ORDINÆRT_FORSKUDD("75", "Ordinært forskudd"),
    DELT_BOSTED_NETTO("8DN", "Delt bosted-netto"),
    RESULTAT_FRA_ANNET_VEDTAK("RAV", "Resultat fra annet vedtak"),
    AVSLAG_PRIVAT_AVTALE_OM_BIDRAG("APA", "Avslag, på grunn av privat avtale om bidrag"),
    OPPHØR_PRIVAT_AVTALE_OM_BIDRAG("OPA", "Opphør, på grunn av privat avtale om bidrag"),
    AVSLAG_IKKE_INNKREVING_AV_BIDRAG("AIB", "Avslag, ikke innkreving av bidrag"),
    OPPHØR_IKKE_INNKREVING_AV_BIDRAG("OIB", "Opphør, ikke innkreving av bidrag"),
    AVSLAG_IKKE_REGISTRERT_PÅ_ADRESSE("ARA", "Avslag, ikke registrert på adresse"),
    OPPHØR_IKKE_REGISTRERT_PÅ_ADRESSE("ORA", "Opphør, ikke registrert på adresse"),
    PRIVAT_AVTALE_OM_SÆRBIDRAG("APS", "Privat avtale om særbidrag"),
    AVSLAG_BIDRAGSPLIKTIG_ER_DØD("BPD", "Avslag, bidragspliktig er død"),
    AVSLAG_IKKE_OMSORG_FOR_BARNET("IOB", "Avslag, ikke omsorg for barnet"),
    OPPHØR_PARTEN_BER_OM_OPPHØR("OPB", "Opphør, parten ber om opphør"),
    AVSLAG_IKKE_DOKUMENTERT_SKOLEGANG("ADS", "Avslag, ikke dokumentert skolegang"),
    OPPHØR_AVSLUTTET_SKOLEGANG("OSG", "Opphør, avsluttet skolegang"),
    IKKE_STERK_NOK_GRUNN_OG_BIDRAGET_HAR_OPPHØRT("OSB", "Ikke sterk nok grunn og bidraget har opphørt"),
    BIDRAGSMOTTAKER_HAR_OMSORG_FOR_BARNET("AOB", "Bidragsmottaker har omsorg for barnet"),
    OPPHØR_BARNET_ER_DØDT("OBD", "Opphør, barnet er dødt"),
    TRUKKET_FORHOLDSMESSIG_FORDELING("AFF", "Trukket forholdsmessig fordeling"),
    AVSLAG_PARTENE_BOR_SAMMEN("APB", "Avslag, partene bor sammen"),
    OPPHØR_PARTENE_BOR_SAMMEN("OPS", "Opphør, partene bor sammen"),
    ;

    companion object {
        fun fraKode(kode: String): Beslutningsårsak? =
            try {
                Beslutningsårsak.entries.find { res -> res.bisysKode == kode }
                    ?: Beslutningsårsak.valueOf(kode)
            } catch (e: Exception) {
                null
            }
    }
}
