package no.nav.bidrag.domene.enums.behandling

import io.swagger.v3.oas.annotations.media.Schema
import kotlin.enums.enumEntries

// Enum verdier av tabellen T_KODE_HEND_TYPE i bisys
@Schema(enumAsRef = true)
enum class HendelseType(
    val kode: String,
    val beskrivelse: String,
    val gyldig: Boolean = true,
) {
    AVSLUTTET("ASLU", "Avsluttet"),
    AUTOMATISK_AVSLAG("AUAV", "Automatisk avslag"),
    AVVIST("AV", "Avvist"),
    BRUKERSTØTTE("BRUS", "Brukerstøtte", false),
    DØMT_AVSLUTTET("DM", "Dømt avsluttet"),
    ENDRING_BARN_OVER_18("ENBB", "Endring Barn>18"),
    ENDRING_KOMMUNE("ENKU", "Endring kommune"),
    ENDRING_BM("ENMO", "Endring BM"),
    ENDRING_NORSKE_MYNDIGHETER("ENNM", "Endring Norske myndigh."),
    ENDRING_BP("ENPL", "Endring BP"),
    ENDRING_UTENLANDSKE_MYNDIGHETER("ENUM", "Endring Utenl.myndigh."),
    ENDRING_VERGE("ENVE", "Endring Verge"),
    ERKJENT_AVSLUTTET("ER", "Erkjent avsluttet"),
    EGET_TILTAK_NAV("ETET", "Eget tiltak NAV"),
    EGET_TILTAK_NAV_INTERNASJONALT("ETIN", "Eget tiltak NAV Internasjonalt"),
    EGET_TILTAK_BM("ETMO", "Eget tiltak BM"),
    EGET_TILTAK_BP("ETPL", "Eget tiltak BP"),
    SØKNAD_BARN_OVER_18("FABB", "Søknad Barn>18"),
    SØKNAD_NAV("FAET", "Søknad NAV"),
    SØKNAD_NAV_INTERNASJONALT("FAIN", "Søknad NAV Internasjonalt"),
    SØKNAD_KOMMUNE("FAKU", "Søknad kommune"),
    SØKNAD_BM("FAMO", "Søknad BM"),
    SØKNAD_NORSKE_MYNDIGHETER("FANM", "Søknad Norske myndigh."),
    SØKNAD_BP("FAPL", "Søknad BP"),
    SØKNAD_UTENLANDSKE_MYNDIGHETER("FAUM", "Søknad Utenl.myndigh."),
    SØKNAD_VERGE("FAVE", "Søknad Verge"),
    FEILREGISTRERT("FR", "Feilregistrert"),
    GJELDER_ENDRET("GJEN", "Gjelder endret"),
    G4("G4", "G4"),
    INNKREVINGSGRUNLAG_BARN_OVER_18("IGBB", "Innkrevingsgrl.Barn>18"),
    INNKREVINGSGRUNLAG_FYLKESNEMDA("IGFN", "Innkrevingsgrl.Fylkesnemda"),
    INNKREVINGSGRUNLAG_BM("IGMO", "Innkrevingsgrl.BM"),
    INNKREVINGSGRUNLAG_NORSKE_MYNDIGHETER("IGNM", "Innkrevingsgrl.Norsk.myndigh."),
    INNKREVINGSGRUNLAG_BP("IGPL", "Innkrevingsgrl.BP"),
    INNKREVINGSGRUNLAG_UTENLANDSKE_MYNDIGHETER("IGUM", "Innkrevingsgrl.Utl.myndigh."),
    INNKREVINGSGRUNLAG_VERGE("IGVE", "Innkrevingsgrl.Verge"),
    INDEKSREGULERT("IRET", "Indeksregulert"),
    INDEKSREGULERT_KOMMUNE("IRKO", "Indeksregulert", false),
    INDEKSREGULERT_UTENLANDSKE_MYNDIGHETER("IRUM", "Ind.reg. Utl.myndigh."),
    KLAGE_BEGRENSET_BM_I_ANNEN_SAK("KBAS", "Klage begrenset BM i annen sak"),
    KLAGE_BEGRENSET_BARN_OVER_18("KBBB", "Klage begrenset Barn>18"),
    KLAGE_BEGRENSET_SATS_BM("KBMO", "Klage begrenset sats BM"),
    KLAGE_BEGRENSET_NORSK_MYNDIGHET("KBNM", "Klage begrenset Norsk myndighet"),
    KLAGE_BEGRENSET_SATS_BP("KBPL", "Klage begrenset sats BP"),
    KLAGE_BEGRENSET_UTENLANDSK_MYNDIGHET("KBUM", "Klage begrenset Utenl.myndighet"),
    KLAGE_BEGRENSET_SATS_VERGE("KBVE", "Klage begrenset sats Verge"),
    KLAGE_BM_I_ANNEN_SAK("KLAS", "Klage BM annen sak"),
    KLAGE_BARN_OVER_18("KLBB", "Klage Barn>18"),
    KLAGE_NAV("KLET", "Klage NAV"),
    KLAGE_FYLKESNEMDA("KLFN", "Klage Fylkesnemda"),
    KLAGE_KOMMUNE("KLKU", "Klage kommune"),
    KLAGE_BM("KLMO", "Klage BM"),
    KLAGE_NORSK_MYNDIGHET("KLNM", "Klage Norsk myndighet"),
    KLAGE_BP("KLPL", "Klage BP"),
    KLAGE_UTENLANDSK_MYNDIGHET("KLUM", "Klage Utenl. myndighet"),
    KLAGE_VERGE("KLVE", "Klage Verge"),
    FØLGER_KLAGE_BM_I_ANNEN_SAK("KMAS", "Følger klage BM i annen sak"),
    FØLGER_KLAGE_BARN_OVER_18("KMBB", "Følger klage Barn>18"),
    FØLGER_KLAGE_BM("KMMO", "Følger klage BM"),
    FØLGER_KLAGE_NORSK_MYNDIGHET("KMNM", "Følger klage Norsk myndighet"),
    FØLGER_KLAGE_BP("KMPL", "Følger klage BP"),
    FØLGER_KLAGE_UTENLANDSK_MYNDIGHET("KMUM", "Følger klage Utenl. Myndighet"),
    FØLGER_KLAGE_VERGE("KMVE", "Følger klage Verge"),
    KONVENSJONSKOДЕ_REGISTRERT("KORE", "Konvensjonskode registrert"),
    OMGJØRING_BEGRENSET_SATS("OBET", "Omgjøring begr.sats"),
    OPPJUSTERING_11_ÅR("OF11", "Oppjustering 11    år"),
    OPPHØR_BARN_OVER_18("OHBB", "Opphør Barn > 18"),
    OPPHØR_NAV("OHET", "Opphør NAV"),
    OPPHØR_FYLKESNEMDA("OHFN", "Opphør Fylkesnemda"),
    OPPHØR_KOMMUNE("OHKU", "Opphør kommune"),
    OPPHØR_BM("OHMO", "Opphør BM"),
    OPPHØR_BP("OHPL", "Opphør BP"),
    OPPHØR_UTENLANDSKE_MYNDIGHETER("OHUM", "Opphør Utl.myndigh."),
    OPPHØR_VERGE("OHVE", "Opphør Verge"),
    OMGJØRING_EGET_TILTAK("OM", "Omgjøring eget tiltak"),
    OMGJØRING_EGET_TILTAK_NAV("OMET", "Omgjøring eget tiltak NAV"),
    PRIVAT_AVTALE_BARN_OVER_18("PABB", "Privat avtale Barn>18"),
    PRIVAT_AVTALE_FYLKESNEMDA("PAFN", "Privat avtale Fylkesnemda"),
    PRIVAT_AVTALE_BM("PAMO", "Privat avtale BM"),
    PRIVAT_AVTALE_BP("PAPL", "Privat avtale BP"),
    PRIVAT_AVTALE_UTENLANDSKE_MYNDIGHETER("PAUM", "Privat avtale Utenl.myndighet"),
    PRIVAT_AVTALE_VERGE("PAVE", "Privat avtale Verge"),
    BEGRENSET_REVURDERING_NAV("RBET", "Begr.revurdering NAV"),
    REFERANSENUMMER_REGISTRERT("RERE", "Referansenr.registrert"),
    ALDERSJUSTERING("AJET", "Aldersjustering"),
    SAK_AVSLUTTET("AVSL", "Sak avsluttet"),
    SAK_GJENÅPNET("GJAP", "Sak gjenåpnet"),
    SAK_GJENÅPNET_MIDLERTIDIG("GJAM", "Sak gjenåpnet midlertidig"),
    REVURDERING_NAV("RFET", "Revurdering NAV"),
    REVURDERING_NAV_INTERNASJONALT("RFIN", "Revurdering NAV Internasjonalt"),
    REVURDERING_BM("RFMO", "Revurdering BM"),
    REVURDERING_BP("RFPL", "Revurdering BP"),
    STOPPET_BARN_FYLLER_18("ST18", "Stoppet. Barn fyller 18"),
    SENDT_UTLANDET("SU", "Sendt utlandet"),
    TRUKKET("TR", "Trukket"),
    VEDTAK_BARN_OVER_18("VEBB", "Vedtak Barn>18"),
    VEDTAK_BM("VEBM", "Vedtak BM"),
    VEDTAK_BP("VEBP", "Vedtak BP"),
    VEDTAK("VEDT", "Vedtak"),
    VEDTAK_FTK("VEFK", "Vedtak FTK"),
    VEDTAK_FYLKESNEMDA("VEFN", "Vedtak Fylkesnemda"),
    VEDTAK_FRA_BOST("VEKO", "Vedtak fra BOST", false),
    VEDTAK_KOMMUNE("VEKU", "Vedtak kommune"),
    VEDTAK_MIDLERTIDIG("VEMI", "Vedtak Midlertidig"),
    VEDTAK_UTENLANDSKE_MYNDIGHETER("VEUM", "Vedtak Utl.myndigh."),
    VEDTAK_VERGE("VEVE", "Vedtak Verge"),
    VEDTAKSFORSLAG("VEFO", "Vedtaksforslag"),
    INNKREVINGSVEDTAK("VEIN", "Innkrevingsvedtak"),
    PARAGRAF_35C("35ET", "§ 35c"),
    PARAGRAF_35C_BEGRENSET_SATS("3BET", "§ 35c begrenset sats"),
    KLAGEVEDTAK("VEKL", "Klagevedtak"),
    OMGJØRINGSVEDTAK("VEOM", "Omgjøringsvedtak"),
    FORHOLDSMESSIG_FORDELING("FFET", "Forholdsmessig fordeling"),
    REVURDERING_TRUKKET("RTET", "Revurdering trukket"),
    FORHOLDSMESSIG_FORDELING_KLAGE("FKET", "Forholdsmessig fordeling klage"),
    ;

    companion object {
        fun fraKode(kode: String): HendelseType? =
            try {
                HendelseType.entries.find { it.kode == kode } ?: HendelseType.valueOf(kode)
            } catch (e: Exception) {
                null
            }
    }
}
