package no.nav.bidrag.domene.enums.beregning

enum class Avvikstype {
    PERIODER_OVERLAPPER,
    PERIODER_HAR_OPPHOLD,
    NULL_VERDI_I_DATO,
    DATO_FOM_ETTER_DATO_TIL,
    PERIODE_MANGLER_DATA,
    DAG_ER_IKKE_FØRSTE_DAG_I_MND,
    UGYLDIG_INNTEKT_TYPE,
    UGYLDIG_INNTEKT_PERIODE,
    OVERLAPPENDE_INNTEKT,
}
