package no.nav.bidrag.domene.enums.grunnlag

import io.swagger.v3.oas.annotations.media.Schema

/**
 * Typer grunnlag som benyttes i behandling
 */
@Schema(enumAsRef = true)
enum class Grunnlagstype {
    SÆRFRADRAG,
    SKATTEKLASSE,
    BARN_I_HUSSTAND,
    BOSTATUS,
    BOSTATUS_BP,
    INNTEKT,
    INNTEKT_BARN,
    INNTEKT_UTVIDET_BARNETRYGD,
    KAPITALINNTEKT,
    KAPITALINNTEKT_BARN,
    NETTO_SÆRTILSKUDD,
    SAMVÆRSKLASSE,
    BIDRAGSEVNE,
    SAMVÆRSFRADRAG,
    SJABLON,
    LØPENDE_BIDRAG,
    FAKTISK_UTGIFT,
    BARNETILSYN_MED_STØNAD,
    FORPLEINING_UTGIFT,
    BARN,
    SIVILSTAND,
    BARNETILLEGG,
    BARNETILLEGG_FORSVARET,
    DELT_BOSTED,
    NETTO_BARNETILSYN,
    UNDERHOLDSKOSTNAD,
    BPS_ANDEL_UNDERHOLDSKOSTNAD,
    TILLEGGSBIDRAG,
    MAKS_BIDRAG_PER_BARN,
    BPS_ANDEL_SÆRTILSKUDD,
    MAKS_GRENSE_25_INNTEKT,
    GEBYRFRITAK,
    INNBETALT_BELØP,
    FORHOLDSMESSIG_FORDELING,
    SLUTTBEREGNING_BBM,
    KLAGE_STATISTIKK,
    PERSON,
    BOSTATUS_PERIODE,
    SØKNAD,
    SIVILSTAND_PERIODE,
    VIRKNINGSDATO,
    NOTAT,

    // Grunnlagdata er ulik for beregning og vedtak. Derfor finnes det to ulike enum verdier for "INNTEKT_RAPPORTERING_PERIODE"
    BEREGNING_INNTEKT_RAPPORTERING_PERIODE,
    INNTEKT_RAPPORTERING_PERIODE,

    INNHENTET_HUSSTANDSMEDLEM_PERIODE,
    INNHENTET_SIVILSTAND_PERIODE,
    INNHENTET_ARBEIDSFORHOLD_PERIODE,

    INNHENTET_INNTEKT_SKATTEGRUNNLAG_PERIODE,
    INNHENTET_INNTEKT_AORDNING_PERIODE,
    INNHENTET_INNTEKT_BARNETILLEGG_PERIODE,
    INNHENTET_INNTEKT_KONTANTSTØTTE_PERIODE,
    INNHENTET_INNTEKT_AINNTEKT_PERIODE,
    INNHENTET_INNTEKT_BARNETILSYN_PERIODE,
    INNHENTET_INNTEKT_SMÅBARNSTILLEGG_PERIODE,
    INNHENTET_INNTEKT_UTVIDETBARNETRYGD_PERIODE,
}
