package no.nav.bidrag.generer.testdata.adresse

@Suppress("unused")
fun genererGatenavn(): String = gatenavn.random()

@Suppress("unused")
fun genererPoststed(): Poststed = poststeder.random()

@Suppress("unused")
fun genererHusnummer(): String = "${(1..999).random()}" + husnummer.random()

fun genererAdresse(): String = "${genererGatenavn()} ${genererHusnummer()}"

fun genererAdresseMedPoststed(): String = "${genererAdresse()}, ${genererPoststed()}"

private val gatenavn =
    listOf(
        "Algarheimsvegen",
        "Allergotvegen",
        "Artilleristubben",
        "Asfaltvegen",
        "Bahustunet",
        "Bakkevegen",
        "Balder Allé",
        "Bekkefaret",
        "Bekkestien",
        "Bergmo",
        "Bergstubben",
        "Bergvollstubben",
        "Birkelundvegen",
        "Bjørkebo",
        "Bjørkebovegen",
        "Bjørkestubben",
        "Bjørkevegen",
        "Bjørmoen",
        "Bjørmofaret",
        "Blikkvegen",
        "Blåbærtråkket",
        "Blåklokkevegen",
        "Blåveisringen",
        "Bonntjennsvegen",
        "Brages Veg",
        "Brannmannsvegen",
        "Brinken",
        "Brinkvegen",
        "Bråtenvegen",
        "Bråtestubben",
        "Bråtesvingen",
        "Bråtevegen",
        "Cathinka Guldbergsveg",
        "Charles Kings Veg",
        "Dagsjøvegen",
        "Dahlrasten",
        "Damvegen",
        "Dragonstien",
        "Dølihagan",
        "Dølivegen",
        "Ekornkroken",
        "Ekornrudvegen",
        "Elektrovegen",
        "Elgtrekket",
        "Elgvegen",
        "Energivegen",
        "Erling Grønlands Veg",
        "Finholtvegen",
        "Fiolvegen",
        "Fjellvegen",
        "Fladbyseter",
        "Flatavegen",
        "Flatmark",
        "Franstuvegen",
        "Furuholtvegen",
        "Furumovegen",
        "Furuseth",
        "Furusethgata",
        "Furuvegen",
        "Gamle Algarheimsveg",
        "Gamle Gardermoveg",
        "Gamle Trondheimsveg",
        "Gardermovegen",
        "Gartnerstubben",
        "Geitramsvegen",
        "Gislevollvegen",
        "Gotaasalleen",
        "Granvegen",
        "Grenaderstubben",
        "Grevlingvegen",
        "Grorudholtet",
        "Grovavegen",
        "Grønnbekkvegen",
        "Gyastubben",
        "Gystad",
        "H Nestens Veg",
        "Hagavegen",
        "Hans M Gystads Veg",
        "Harestien",
        "Haug Allé",
        "Haugan Nord",
        "Haugan Syd",
        "Hestehagen",
        "Hestehovstien",
        "Hesteløkka",
        "Hesteskoen",
        "Holmstubben",
        "Holmsveien",
        "Holtegutua",
        "Holteløkka",
        "Holtestubben",
        "Hovsvingen",
        "Huldreringen",
        "Huldrevegen",
        "Hvitveiskroken",
        "Håndverksvegen",
        "Industrivegen",
        "Infanterisvingen",
        "Jacobsgata",
        "Jerpevegen",
        "Julius Dahlsveg",
        "Jørgenstuvegen",
        "Jørnstuvegen",
        "Karibakken",
        "Karisvingen",
        "Karl B.nordbys Veg",
        "Karl Norbecks Veg",
        "Kjeld Stubs Veg",
        "Kløvervegen",
        "Kongletoppen",
        "Konvallvegen",
        "Korsmovegen",
        "Krokfossvegen",
        "Krusestubben",
        "Krusestuvegen",
        "Krusesvingen",
        "Kverndalsvegen",
        "Kvernlivegen",
        "Laakesetervegen",
        "Langelandsfjellet",
        "Langemovegen",
        "Laubakken",
        "Leirvegen",
        "Lerkelunden",
        "Liavegen",
        "Lievegen",
        "Linjevegen",
        "Linneavegen",
        "Løkkavegen",
        "M Jul Halvorsens Veg",
        "Maiblomvegen",
        "Major O Laakes Veg",
        "Manesjen",
        "Markvegen",
        "Martin Løkens Veg",
        "Maurstien",
        "Midtskogvegen",
        "Mikalsrud",
        "Miltangen",
        "Movegen",
        "Myrtangvegen",
        "Myrvegen",
        "Nedre Lerkeveg",
        "Nedre Solhellinga",
        "Nissetoppen",
        "Nordbyringen",
        "Nordbystien",
        "Nordbysvingen",
        "Nordbytunet",
        "Nordbyvegen",
        "Nordskog",
        "Næringsparkveien",
        "O.a. Kneppes Veg",
        "Oberst Kruses Veg",
        "Ole Reistads Veg",
        "Oppløpssiden",
        "Orresvingen",
        "Paradeplassen",
        "Paradevegen",
        "Parktoppen",
        "Parkvegen",
        "Peder Wætthens Veg",
        "Porten",
        "Rambydalsvegen",
        "Revfaret",
        "Ringvegen",
        "Rismostubben",
        "Rismovegen",
        "Romsaas Allé",
        "Romsaasbakken",
        "Rugdevegen",
        "Rådhusvegen",
        "Rådyrstien",
        "Røsslyngvegen",
        "Sandbakken",
        "Sandmovegen",
        "Sandshagan",
        "Sandsvegen",
        "Sjøbergvegen",
        "Skogheimvegen",
        "Skoglund",
        "Skogmorabben",
        "Skogmotoppen",
        "Skogmovegen",
        "Skogstien",
        "Skogstjernevegen",
        "Skogvegen",
        "Skolevegen",
        "Skånevegen",
        "Slettavegen",
        "Slettmark",
        "Smedalsvegen",
        "Smedalsvingen",
        "Solbakken",
        "Solbergsvingen",
        "Solheimvegen",
        "Solliavegen",
        "Stallkroken",
        "Stallvegen",
        "Stensvegen",
        "Storgata",
        "Stussenvegen",
        "Sundbyjordet",
        "Svenskestuvegen",
        "Såvegen",
        "Sørenstuvegen",
        "Sørholtstubben",
        "Sørholtsvingen",
        "Sørholtvegen",
        "Tiurkroken",
        "Tivolisvingen",
        "Tjerngløtt",
        "Tranevegen",
        "Travalleen",
        "Travbanevegen",
        "Trondheimsvegen",
        "Tungen",
        "Tverrvegen",
        "Tyristubben",
        "Tyrivegen",
        "Tyttebærlia",
        "Tømmervegen",
        "Ursins Veg",
        "Valhallavegen",
        "Vangsveien",
        "Vannvegen",
        "Veiberggata",
        "Verkensvegen",
        "Veslevegen",
        "Vestlia",
        "Vestre Solhellinga",
        "Vetteringen",
        "Vettevegen",
        "Vilbergvegen",
        "Vintervegen",
        "Vårvegen",
        "Yttervegen",
        "Åsmoen",
        "Åsmostubben",
        "Øvre Damveg",
        "Øvre Lerkeveg",
        "Øvre Solhellinga",
    )

private val poststeder =
    listOf(
        Poststed("1300", "SANDVIKA"),
        Poststed("1301", "SANDVIKA"),
        Poststed("1302", "SANDVIKA"),
        Poststed("1303", "SANDVIKA"),
        Poststed("1304", "SANDVIKA"),
        Poststed("1305", "HASLUM"),
        Poststed("1306", "SANDVIKA"),
        Poststed("1307", "FORNEBU"),
        Poststed("1308", "JAR"),
        Poststed("1309", "RUD"),
        Poststed("1311", "HØVIKODDEN"),
        Poststed("1312", "SLEPENDEN"),
        Poststed("1313", "VØYENENGA"),
        Poststed("1314", "VØYENENGA"),
        Poststed("1316", "EIKSMARKA"),
        Poststed("1317", "BÆRUMS VERK"),
        Poststed("1318", "BEKKESTUA"),
        Poststed("1319", "BEKKESTUA"),
        Poststed("1321", "STABEKK"),
        Poststed("1322", "HØVIK"),
        Poststed("1323", "HØVIK"),
        Poststed("1324", "LYSAKER"),
        Poststed("1325", "LYSAKER"),
        Poststed("1326", "LYSAKER"),
        Poststed("1327", "LYSAKER"),
        Poststed("1328", "HØVIK"),
        Poststed("1329", "LOMMEDALEN"),
        Poststed("1330", "FORNEBU"),
        Poststed("1331", "FORNEBU"),
        Poststed("1332", "ØSTERÅS"),
        Poststed("1333", "KOLSÅS"),
        Poststed("1334", "RYKKINN"),
        Poststed("1335", "SNARØYA"),
        Poststed("1336", "SANDVIKA"),
        Poststed("1337", "SANDVIKA"),
        Poststed("1338", "SANDVIKA"),
        Poststed("1339", "VØYENENGA"),
        Poststed("1340", "SKUI"),
        Poststed("1341", "SLEPENDEN"),
        Poststed("1342", "GJETTUM"),
        Poststed("1344", "HASLUM"),
        Poststed("1346", "GJETTUM"),
        Poststed("1348", "RYKKINN"),
        Poststed("1349", "RYKKINN"),
        Poststed("1350", "LOMMEDALEN"),
        Poststed("1351", "RUD"),
        Poststed("1352", "KOLSÅS"),
        Poststed("1353", "BÆRUMS VERK"),
        Poststed("1354", "BÆRUMS VERK"),
        Poststed("1356", "BEKKESTUA"),
        Poststed("1357", "BEKKESTUA"),
        Poststed("1358", "JAR"),
        Poststed("1359", "EIKSMARKA"),
        Poststed("1360", "FORNEBU"),
        Poststed("1361", "ØSTERÅS"),
        Poststed("1362", "HOSLE"),
        Poststed("1363", "HØVIK"),
        Poststed("1364", "FORNEBU"),
        Poststed("1365", "BLOMMENHOLM"),
        Poststed("1366", "LYSAKER"),
        Poststed("1367", "SNARØYA"),
        Poststed("1368", "STABEKK"),
        Poststed("1369", "STABEKK"),
        Poststed("1371", "ASKER"),
        Poststed("1372", "ASKER"),
        Poststed("1373", "ASKER"),
        Poststed("1375", "BILLINGSTAD"),
        Poststed("1376", "BILLINGSTAD"),
        Poststed("1377", "BILLINGSTAD"),
        Poststed("1378", "NESBRU"),
        Poststed("1379", "NESBRU"),
        Poststed("1380", "HEGGEDAL"),
        Poststed("1381", "VETTRE"),
        Poststed("1383", "ASKER"),
        Poststed("1384", "ASKER"),
        Poststed("1385", "ASKER"),
        Poststed("1386", "ASKER"),
        Poststed("1387", "ASKER"),
        Poststed("1388", "BORGEN"),
        Poststed("1389", "HEGGEDAL"),
        Poststed("1390", "VOLLEN"),
        Poststed("1391", "VOLLEN"),
        Poststed("1392", "VETTRE"),
        Poststed("1393", "VOLLEN"),
        Poststed("1394", "NESBRU"),
        Poststed("1395", "HVALSTAD"),
        Poststed("1396", "BILLINGSTAD"),
        Poststed("1397", "NESØYA"),
        Poststed("1399", "ASKER"),
        Poststed("1400", "SKI"),
        Poststed("1401", "SKI"),
        Poststed("1402", "SKI"),
        Poststed("1403", "LANGHUS"),
        Poststed("1404", "SIGGERUD"),
        Poststed("1405", "LANGHUS"),
        Poststed("1406", "SKI"),
        Poststed("1407", "VINTERBRO"),
        Poststed("1408", "KRÅKSTAD"),
        Poststed("1409", "SKOTBU"),
        Poststed("1410", "KOLBOTN"),
        Poststed("1411", "KOLBOTN"),
        Poststed("1412", "SOFIEMYR"),
        Poststed("1413", "TÅRNÅSEN"),
        Poststed("1414", "TROLLÅSEN"),
        Poststed("1415", "OPPEGÅRD"),
        Poststed("1416", "OPPEGÅRD"),
        Poststed("1417", "SOFIEMYR"),
        Poststed("1418", "KOLBOTN"),
        Poststed("1419", "OPPEGÅRD"),
        Poststed("1420", "SVARTSKOG"),
        Poststed("1421", "TROLLÅSEN"),
        Poststed("1422", "SIGGERUD"),
        Poststed("1423", "SKI"),
        Poststed("1424", "SKI"),
        Poststed("1425", "SKI"),
        Poststed("1429", "VINTERBRO"),
        Poststed("1430", "ÅS"),
        Poststed("1431", "ÅS"),
        Poststed("1432", "ÅS"),
        Poststed("1433", "ÅS"),
        Poststed("1434", "ÅS"),
        Poststed("1435", "ÅS"),
        Poststed("1440", "DRØBAK"),
        Poststed("1441", "DRØBAK"),
        Poststed("1442", "DRØBAK"),
        Poststed("1443", "DRØBAK"),
        Poststed("1444", "DRØBAK"),
        Poststed("1445", "DRØBAK"),
        Poststed("1446", "DRØBAK"),
        Poststed("1447", "DRØBAK"),
        Poststed("1448", "DRØBAK"),
        Poststed("1449", "DRØBAK"),
        Poststed("1450", "NESODDTANGEN"),
        Poststed("1451", "NESODDTANGEN"),
        Poststed("1452", "NESODDTANGEN"),
        Poststed("1453", "BJØRNEMYR"),
        Poststed("1454", "FAGERSTRAND"),
        Poststed("1455", "NORDRE FROGN"),
        Poststed("1456", "NESODDTANGEN"),
        Poststed("1457", "FAGERSTRAND"),
        Poststed("1458", "FJELLSTRAND"),
        Poststed("1459", "NESODDEN"),
        Poststed("1461", "LØRENSKOG"),
        Poststed("1462", "FJELLHAMAR"),
        Poststed("1463", "FJELLHAMAR"),
        Poststed("1464", "FJELLHAMAR"),
        Poststed("1465", "STRØMMEN"),
        Poststed("1466", "STRØMMEN"),
        Poststed("1467", "STRØMMEN"),
        Poststed("1468", "FINSTADJORDET"),
        Poststed("1469", "RASTA"),
        Poststed("1470", "LØRENSKOG"),
        Poststed("1471", "LØRENSKOG"),
        Poststed("1472", "FJELLHAMAR"),
        Poststed("1473", "LØRENSKOG"),
        Poststed("1474", "LØRENSKOG"),
        Poststed("1475", "FINSTADJORDET"),
        Poststed("1476", "RASTA"),
        Poststed("1477", "FJELLHAMAR"),
        Poststed("1478", "LØRENSKOG"),
        Poststed("1479", "KURLAND"),
        Poststed("1480", "SLATTUM"),
        Poststed("1481", "HAGAN"),
        Poststed("1482", "NITTEDAL"),
        Poststed("1483", "HAGAN"),
        Poststed("1484", "HAKADAL"),
        Poststed("1485", "HAKADAL"),
        Poststed("1486", "NITTEDAL"),
        Poststed("1487", "HAKADAL"),
        Poststed("1488", "HAKADAL"),
        Poststed("1501", "MOSS"),
        Poststed("1502", "MOSS"),
        Poststed("1503", "MOSS"),
        Poststed("1504", "MOSS"),
        Poststed("1506", "MOSS"),
        Poststed("1508", "MOSS"),
        Poststed("1509", "MOSS"),
        Poststed("1510", "MOSS"),
        Poststed("1511", "MOSS"),
        Poststed("1512", "MOSS"),
        Poststed("1513", "MOSS"),
        Poststed("1514", "MOSS"),
        Poststed("1515", "MOSS"),
        Poststed("1516", "MOSS"),
        Poststed("1517", "MOSS"),
        Poststed("1518", "MOSS"),
        Poststed("1519", "MOSS"),
        Poststed("1520", "MOSS"),
        Poststed("1521", "MOSS"),
        Poststed("1522", "MOSS"),
        Poststed("1523", "MOSS"),
        Poststed("1524", "MOSS"),
        Poststed("1525", "MOSS"),
        Poststed("1526", "MOSS"),
        Poststed("1528", "MOSS"),
        Poststed("1529", "MOSS"),
        Poststed("1530", "MOSS"),
        Poststed("1531", "MOSS"),
        Poststed("1532", "MOSS"),
        Poststed("1533", "MOSS"),
        Poststed("1534", "MOSS"),
        Poststed("1535", "MOSS"),
        Poststed("1536", "MOSS"),
        Poststed("1537", "MOSS"),
        Poststed("1538", "MOSS"),
        Poststed("1539", "MOSS"),
        Poststed("1540", "VESTBY"),
        Poststed("1541", "VESTBY"),
        Poststed("1542", "VESTBY"),
        Poststed("1543", "VESTBY"),
        Poststed("1544", "VESTBY"),
        Poststed("1545", "HVITSTEN"),
        Poststed("1550", "HØLEN"),
        Poststed("1555", "SON"),
        Poststed("1556", "SON"),
        Poststed("1560", "LARKOLLEN"),
        Poststed("1561", "LARKOLLEN"),
        Poststed("1570", "DILLING"),
        Poststed("1580", "RYGGE"),
        Poststed("1581", "RYGGE"),
        Poststed("1590", "RYGGE"),
        Poststed("1591", "SPERREBOTN"),
        Poststed("1592", "VÅLER I ØSTFOLD"),
        Poststed("1593", "SVINNDAL"),
        Poststed("1594", "VÅLER I ØSTFOLD"),
        Poststed("1596", "MOSS"),
        Poststed("1597", "MOSS"),
        Poststed("1598", "MOSS"),
        Poststed("1599", "MOSS"),
        Poststed("1601", "FREDRIKSTAD"),
        Poststed("1602", "FREDRIKSTAD"),
        Poststed("1604", "FREDRIKSTAD"),
        Poststed("1605", "FREDRIKSTAD"),
        Poststed("1606", "FREDRIKSTAD"),
        Poststed("1607", "FREDRIKSTAD"),
        Poststed("1608", "FREDRIKSTAD"),
        Poststed("1609", "FREDRIKSTAD"),
        Poststed("1610", "FREDRIKSTAD"),
        Poststed("1612", "FREDRIKSTAD"),
        Poststed("1613", "FREDRIKSTAD"),
        Poststed("1614", "FREDRIKSTAD"),
        Poststed("1615", "FREDRIKSTAD"),
        Poststed("1616", "FREDRIKSTAD"),
        Poststed("1617", "FREDRIKSTAD"),
        Poststed("1618", "FREDRIKSTAD"),
        Poststed("1619", "FREDRIKSTAD"),
        Poststed("1620", "GRESSVIK"),
        Poststed("1621", "GRESSVIK"),
        Poststed("1622", "GRESSVIK"),
        Poststed("1623", "GRESSVIK"),
        Poststed("1624", "GRESSVIK"),
        Poststed("1625", "MANSTAD"),
        Poststed("1626", "MANSTAD"),
        Poststed("1628", "ENGELSVIKEN"),
        Poststed("1629", "GAMLE FREDRIKSTAD"),
        Poststed("1630", "GAMLE FREDRIKSTAD"),
        Poststed("1632", "GAMLE FREDRIKSTAD"),
        Poststed("1633", "GAMLE FREDRIKSTAD"),
        Poststed("1634", "GAMLE FREDRIKSTAD"),
        Poststed("1636", "GAMLE FREDRIKSTAD"),
        Poststed("1637", "GAMLE FREDRIKSTAD"),
        Poststed("1638", "GAMLE FREDRIKSTAD"),
        Poststed("1639", "GAMLE FREDRIKSTAD"),
        Poststed("1640", "RÅDE"),
        Poststed("1641", "RÅDE"),
        Poststed("1642", "SALTNES"),
        Poststed("1643", "RÅDE"),
        Poststed("1650", "SELLEBAKK"),
        Poststed("1651", "SELLEBAKK"),
        Poststed("1653", "SELLEBAKK"),
        Poststed("1654", "SELLEBAKK"),
        Poststed("1655", "SELLEBAKK"),
        Poststed("1657", "TORP"),
        Poststed("1658", "TORP"),
        Poststed("1659", "TORP"),
        Poststed("1661", "ROLVSØY"),
        Poststed("1662", "ROLVSØY"),
        Poststed("1663", "ROLVSØY"),
        Poststed("1664", "ROLVSØY"),
        Poststed("1665", "ROLVSØY"),
        Poststed("1666", "ROLVSØY"),
        Poststed("1667", "ROLVSØY"),
        Poststed("1670", "KRÅKERØY"),
        Poststed("1671", "KRÅKERØY"),
        Poststed("1672", "KRÅKERØY"),
        Poststed("1673", "KRÅKERØY"),
        Poststed("1675", "KRÅKERØY"),
        Poststed("1676", "KRÅKERØY"),
        Poststed("1678", "KRÅKERØY"),
        Poststed("1679", "KRÅKERØY"),
        Poststed("1680", "SKJÆRHALDEN"),
        Poststed("1682", "SKJÆRHALDEN"),
        Poststed("1683", "VESTERØY"),
        Poststed("1684", "VESTERØY"),
        Poststed("1690", "HERFØL"),
        Poststed("1692", "NEDGÅRDEN"),
        Poststed("1701", "SARPSBORG"),
        Poststed("1702", "SARPSBORG"),
        Poststed("1703", "SARPSBORG"),
        Poststed("1704", "SARPSBORG"),
    )

private val husnummer = listOf(
    "",
    "A",
    "B",
    "C",
    "D",
    "E",
)
