name: Bidrag-domene
on:
  push:
    paths:
      - "bidrag-domene/**"

permissions:
  contents: "write"
  id-token: "write"
  packages: "write"

jobs:
  build-and-release:
    name: Build and release package
    uses: ./.github/workflows/build_and_release_package.yml
    with:
      package-name: bidrag-domene
    secrets: inherit