name: Build-Deploy
on:
  push:
    paths:
      - "bidrag-transport/**"
  pull_request:
    types: [closed]

permissions:
  contents: "read"
  id-token: "write"
  packages: "write"

jobs:
  build-and-release:
    name: Build and release package
    uses: ./.github/workflows/build_and_release_package.yml
    with:
      package-name: bidrag-transport
    secrets: inherit