name: Publish artifacts
on:
  release:
    types: [published]

permissions:
  contents: "write"
  id-token: "write"
  packages: "write"

jobs:
  build-and-release:
    name: Build and release package
    uses: navikt/bidrag-workflow/.github/workflows/maven_publish.yaml@main
    with:
      version: ${{ github.event.release.tag_name }}
    secrets: inherit