name: Release Drafter

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev/**
  pull_request:
    types: [opened, reopened, synchronize]

env:
  publish: true

permissions:
  contents: write
  id-token: write
  packages: write
  pull-requests: write

jobs:
  build-release:
    name: "Build and release package"
    uses: navikt/bidrag-workflow/.github/workflows/maven_release_drafter.yaml@main
    secrets: inherit
    with:
      publish: true